- name: Ensure that PasswordAuthentication is set to no in sshd_config
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?\\s*PasswordAuthentication (no|yes)\\s*$"
    line: "PasswordAuthentication no"
    state: present
  notify: sshd restart

